import { useState } from "react";
import { Receipt, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

interface RentReceiptGeneratorProps {
  propertyTitle: string;
  rent: number;
  tenantName?: string;
  ownerName?: string;
}

const RentReceiptGenerator = ({ propertyTitle, rent, tenantName = "", ownerName = "" }: RentReceiptGeneratorProps) => {
  const [tenant, setTenant] = useState(tenantName);
  const [owner, setOwner] = useState(ownerName);
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));

  const handleGenerate = () => {
    if (!tenant || !owner) {
      toast.error("Please enter both names");
      return;
    }

    const monthName = new Date(month + "-01").toLocaleDateString("en-IN", { month: "long", year: "numeric" });

    const html = `
      <!DOCTYPE html>
      <html><head><title>Rent Receipt</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; max-width: 600px; margin: 0 auto; }
        .header { text-align: center; border-bottom: 2px solid #2563eb; padding-bottom: 16px; margin-bottom: 24px; }
        .header h1 { color: #2563eb; font-size: 20px; margin: 0; }
        .header p { color: #888; font-size: 11px; margin: 4px 0 0; }
        .field { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #eee; font-size: 13px; }
        .field .label { color: #666; }
        .field .value { font-weight: 600; color: #333; }
        .amount { text-align: center; margin: 24px 0; padding: 16px; background: #f0f7ff; border-radius: 12px; }
        .amount p { font-size: 28px; font-weight: 800; color: #2563eb; margin: 0; }
        .amount span { font-size: 11px; color: #888; }
        .sig { margin-top: 40px; display: flex; justify-content: space-between; }
        .sig div { text-align: center; }
        .sig .line { width: 140px; border-top: 1px solid #ccc; margin-top: 40px; padding-top: 6px; font-size: 11px; color: #888; }
        .footer { text-align: center; margin-top: 32px; font-size: 10px; color: #aaa; }
      </style></head><body>
        <div class="header">
          <h1>🏠 Rent Receipt</h1>
          <p>Generated by Sahi Jagah</p>
        </div>
        <div class="field"><span class="label">Receipt No.</span><span class="value">RR-${Date.now().toString(36).toUpperCase()}</span></div>
        <div class="field"><span class="label">Date</span><span class="value">${new Date().toLocaleDateString("en-IN")}</span></div>
        <div class="field"><span class="label">Month</span><span class="value">${monthName}</span></div>
        <div class="field"><span class="label">Property</span><span class="value">${propertyTitle}</span></div>
        <div class="field"><span class="label">Tenant</span><span class="value">${tenant}</span></div>
        <div class="field"><span class="label">Owner/Landlord</span><span class="value">${owner}</span></div>
        <div class="amount">
          <span>Amount Paid</span>
          <p>₹${rent.toLocaleString("en-IN")}</p>
        </div>
        <div class="sig">
          <div><div class="line">Tenant Signature</div></div>
          <div><div class="line">Landlord Signature</div></div>
        </div>
        <div class="footer">This is a computer-generated receipt | Sahi Jagah</div>
      </body></html>
    `;

    const w = window.open("", "_blank");
    if (w) {
      w.document.write(html);
      w.document.close();
      w.print();
      toast.success("Receipt generated!");
    }
  };

  const inputClass = "w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring";

  return (
    <div className="bg-card rounded-2xl p-4 shadow-card">
      <div className="flex items-center gap-2 mb-3">
        <Receipt className="h-5 w-5 text-primary" />
        <h3 className="font-bold text-foreground text-sm">Rent Receipt</h3>
      </div>

      <div className="space-y-2">
        <input className={inputClass} placeholder="Tenant Name" value={tenant} onChange={(e) => setTenant(e.target.value)} />
        <input className={inputClass} placeholder="Owner/Landlord Name" value={owner} onChange={(e) => setOwner(e.target.value)} />
        <input className={inputClass} type="month" value={month} onChange={(e) => setMonth(e.target.value)} />
        <Button onClick={handleGenerate} className="w-full gradient-blue text-primary-foreground border-0 gap-2">
          <Download className="h-4 w-4" /> Generate Receipt
        </Button>
      </div>
    </div>
  );
};

export default RentReceiptGenerator;
