// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp, auth } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/search-properties.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function anonClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_properties_default = defineTool({
  name: "search_properties",
  title: "Search properties",
  description: "Search approved (public) property listings on urbanStay. Filter by city, price range, BHK, listing type (rent/sale), or property type. Returns up to 20 matching listings.",
  inputSchema: {
    city: z.string().optional().describe("City name, e.g. 'Hyderabad'."),
    query: z.string().optional().describe("Free-text search across title, description, and locality."),
    min_price: z.number().optional().describe("Minimum price (INR)."),
    max_price: z.number().optional().describe("Maximum price (INR)."),
    bhk: z.number().int().optional().describe("Number of bedrooms (BHK)."),
    listing_type: z.enum(["rent", "sale"]).optional().describe("Rent or sale."),
    property_type: z.string().optional().describe("Property type, e.g. apartment, villa, pg, commercial."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input) => {
    const supabase = anonClient();
    let q = supabase.from("properties").select(
      "id, title, description, price, city, locality, address, bhk, bathrooms, area_sqft, property_type, listing_type, images, is_featured, view_count, created_at"
    ).eq("status", "approved");
    if (input.city) q = q.ilike("city", `%${input.city}%`);
    if (input.min_price != null) q = q.gte("price", input.min_price);
    if (input.max_price != null) q = q.lte("price", input.max_price);
    if (input.bhk != null) q = q.eq("bhk", input.bhk);
    if (input.listing_type) q = q.eq("listing_type", input.listing_type);
    if (input.property_type) q = q.ilike("property_type", `%${input.property_type}%`);
    if (input.query) {
      const like = `%${input.query}%`;
      q = q.or(`title.ilike.${like},description.ilike.${like},locality.ilike.${like}`);
    }
    const { data, error } = await q.order("is_featured", { ascending: false }).order("created_at", { ascending: false }).limit(input.limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: `Search failed: ${error.message}` }], isError: true };
    }
    const results = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify({ count: results.length, results }, null, 2) }],
      structuredContent: { count: results.length, results }
    };
  }
});

// src/lib/mcp/tools/get-property.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function anonClient2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_property_default = defineTool2({
  name: "get_property",
  title: "Get property details",
  description: "Fetch full details of a single approved (public) urbanStay property listing by its ID.",
  inputSchema: {
    id: z2.string().uuid().describe("Property UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = anonClient2();
    const { data, error } = await supabase.from("properties").select("*").eq("id", id).eq("status", "approved").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Lookup failed: ${error.message}` }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "No approved property found with that ID." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { property: data }
    };
  }
});

// src/lib/mcp/tools/list-cities.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
function anonClient3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_cities_default = defineTool3({
  name: "list_cities",
  title: "List cities with listings",
  description: "List all cities that currently have approved (public) urbanStay property listings, with a count per city.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = anonClient3();
    const { data, error } = await supabase.from("properties").select("city").eq("status", "approved").limit(2e3);
    if (error) {
      return { content: [{ type: "text", text: `List failed: ${error.message}` }], isError: true };
    }
    const counts = {};
    for (const row of data ?? []) {
      const c = row.city?.trim();
      if (!c) continue;
      counts[c] = (counts[c] ?? 0) + 1;
    }
    const cities = Object.entries(counts).map(([city, count]) => ({ city, count })).sort((a, b) => b.count - a.count);
    return {
      content: [{ type: "text", text: JSON.stringify({ cities }, null, 2) }],
      structuredContent: { cities }
    };
  }
});

// src/lib/mcp/index.ts
var supabaseUrl = process.env.SUPABASE_URL ?? "";
var mcp_default = defineMcp({
  name: "urbanstay-mcp",
  title: "urbanStay",
  version: "0.1.0",
  instructions: "MCP server for urbanStay, an Indian property rental and sales platform. Sign-in is required. Use `list_cities` to discover cities with active listings, `search_properties` to find approved listings by city, price, BHK, or listing type, and `get_property` to fetch a single listing's full details by ID. Only approved public listings are exposed; per-user data (bookings, messages, wishlists) is not available.",
  auth: auth.oauth.issuer({
    issuer: `${supabaseUrl}/auth/v1`,
    jwksUri: `${supabaseUrl}/auth/v1/.well-known/jwks.json`,
    resource: `${supabaseUrl}/functions/v1/mcp`,
    acceptedAudiences: ["authenticated"],
    resourceName: "urbanStay"
  }),
  tools: [search_properties_default, get_property_default, list_cities_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
